# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'MY_SELL' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
   use_frameworks!
   pod 'LocalLib', :path => 'MYLocalLib'

   pod 'AFNetworking', '~> 3.1.0'
   pod 'MBProgressHUD', '~> 1.0.0'
   pod 'MJRefresh', '~> 3.1.12'
   pod 'SDWebImage', '~> 3.8.2'
   pod 'Masonry' , '~> 1.0.2'

  target 'MY_SELLTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MY_SELLUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
