# Uncomment the next line to define a global platform for your project
 platform :ios, '8.0'

target 'MYLocalLib' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
   use_frameworks!

    pod 'AFNetworking', '~> 3.1.0'
    pod 'MBProgressHUD', '~> 1.0.0'
    pod 'MJRefresh', '~> 3.1.12'
    pod 'SDWebImage', '~> 3.8.2'

  target 'MYLocalLibTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MYLocalLibUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
